/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pertemuan5;

/**
 *
 * @author Alif
 */
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JualBeliHewan extends javax.swing.JFrame {

    Connection conn;
    Statement stmt;

    String DB_URL = "jdbc:postgresql://localhost:5432/PBOKe4";
    String USER = "postgres";
    String PASS = "090406";


    public JualBeliHewan() {
        initComponents();
        connect();
        tampilData();

    }

    public void connect() {
        try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            stmt = conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal : " + e.getMessage());
        }
    }

    public void bersih() {
        tfIDHewan.setText("");
        tfNamaHewan.setText("");
        tfJenisHewan.setText("");
        tfHarga.setText("");
    }

private void tampilData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("id_hewan");
        model.addColumn("nama_hewan");
        model.addColumn("jenis_hewan");
        model.addColumn("harga");
        
        try (
               Connection conn = DriverManager.getConnection(DB_URL, USER, PASS);
                Statement st = conn.createStatement(); 
                ResultSet rs = st.executeQuery("SELECT * FROM petville ORDER BY id_hewan")) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_hewan"),
                    rs.getString("nama_hewan"),
                    rs.getString("jenis_hewan"),
                    rs.getInt("harga"),
                   
                });
            }

            PETVILLE.setModel(model); // tampilkan ke JTable
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
}

    /**
     * Creates new form JualBeliHewan
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Judul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfIDHewan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNamaHewan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfJenisHewan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        Insert = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PETVILLE = new javax.swing.JTable();
        EXIT = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Judul.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Judul.setForeground(new java.awt.Color(255, 255, 255));
        Judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Judul.setText("PETVILLE");
        getContentPane().add(Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 312, 66));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("IDHEWAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 120, 29));

        tfIDHewan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tfIDHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDHewanActionPerformed(evt);
            }
        });
        getContentPane().add(tfIDHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 270, 37));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NAMA HEWAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, 29));

        tfNamaHewan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tfNamaHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaHewanActionPerformed(evt);
            }
        });
        getContentPane().add(tfNamaHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 270, 37));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("JENIS HEWAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 160, 29));

        tfJenisHewan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tfJenisHewan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJenisHewanActionPerformed(evt);
            }
        });
        getContentPane().add(tfJenisHewan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 270, 37));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HARGA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 99, 29));

        tfHarga.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });
        getContentPane().add(tfHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 270, 37));

        Insert.setBackground(new java.awt.Color(204, 255, 255));
        Insert.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Insert.setText("INSERT");
        Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertActionPerformed(evt);
            }
        });
        getContentPane().add(Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, 40));

        Update.setBackground(new java.awt.Color(255, 255, 204));
        Update.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 130, 40));

        Delete.setBackground(new java.awt.Color(255, 255, 204));
        Delete.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, 120, 40));

        Clear.setBackground(new java.awt.Color(204, 255, 255));
        Clear.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Clear.setText("CLEAR");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 110, 40));

        PETVILLE.setAutoCreateRowSorter(true);
        PETVILLE.setBackground(new java.awt.Color(102, 255, 255));
        PETVILLE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PETVILLE.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        PETVILLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " ID HEWAN", "NAMA HEWAN", "JENIS HEWAN", "HARGA"
            }
        ));
        PETVILLE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PETVILLE.setGridColor(new java.awt.Color(0, 0, 0));
        PETVILLE.setSelectionBackground(new java.awt.Color(153, 255, 255));
        PETVILLE.setSelectionForeground(new java.awt.Color(51, 51, 51));
        PETVILLE.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PETVILLE.setShowGrid(true);
        PETVILLE.setSurrendersFocusOnKeystroke(true);
        PETVILLE.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                PETVILLEAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        PETVILLE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PETVILLEMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(PETVILLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 420, 330));

        EXIT.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 560, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pertemuan5/BACKGORUND PETVILLE (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfIDHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDHewanActionPerformed

    private void tfNamaHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaHewanActionPerformed

    private void tfJenisHewanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJenisHewanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJenisHewanActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertActionPerformed
        if (tfIDHewan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi semua data");
        } else if (tfNamaHewan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi semua data");
        } else if (tfJenisHewan.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi semua data");
        } else if (tfHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi semua data");
        } else {
            try {
                String id_hewan = tfIDHewan.getText();
                String nama_hewan = tfNamaHewan.getText();
                String jenis_hewan = tfJenisHewan.getText();
                int harga = Integer.parseInt(tfHarga.getText());

                connect();
                String sql = "INSERT INTO petville (id_hewan, nama_hewan, jenis_hewan, harga) VALUES (?, ?, ?, ?)";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, id_hewan);
                ps.setString(2, nama_hewan);
                ps.setString(3, jenis_hewan);
                ps.setInt(4, harga);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan!");
                tampilData();
                bersih();
            } catch (NumberFormatException | SQLException e) {
                System.out.println("Gagal insert: " + e.getMessage());
            }

        }
    }//GEN-LAST:event_InsertActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        if (tfIDHewan.getText().equals("")
                || tfNamaHewan.getText().equals("")
                || tfJenisHewan.getText().equals("")
                || tfHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Isi semua data");
        } else {
            try {
            String sql = "UPDATE petville SET id_hewan = ?, nama_hewan = ?, jenis_hewan = ?, harga = ? WHERE id_hewan = ?";
            connect();
            PreparedStatement pst = conn.prepareStatement(sql);

            // Ambil dari textfield
            pst.setString(1, tfIDHewan.getText());
            pst.setString(2, tfNamaHewan.getText());
            pst.setString(3, tfJenisHewan.getText());
            pst.setInt(4, Integer.parseInt(tfHarga.getText()));
            pst.setString(5, tfIDHewan.getText()); // ID yang sudah auto increment

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");

            // Refresh tabel
            tampilData();

            bersih();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        try {
            String id_hewan = tfIDHewan.getText();
            String sql = "DELETE FROM petville WHERE id_hewan='" + id_hewan + "'";
            connect();
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");

            // Refresh tabel
            tampilData();

            bersih();

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        bersih();
    }//GEN-LAST:event_ClearActionPerformed

    private void PETVILLEAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_PETVILLEAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_PETVILLEAncestorAdded

    private void PETVILLEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PETVILLEMouseClicked
        int row = PETVILLE.getSelectedRow();
        tfIDHewan.setText(PETVILLE.getValueAt(row, 0).toString());
        tfNamaHewan.setText(PETVILLE.getValueAt(row, 1).toString());
        tfJenisHewan.setText(PETVILLE.getValueAt(row, 2).toString());
        tfHarga.setText(PETVILLE.getValueAt(row, 3).toString());
    }//GEN-LAST:event_PETVILLEMouseClicked

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(JualBeliHewan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JualBeliHewan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Delete;
    private javax.swing.JButton EXIT;
    private javax.swing.JButton Insert;
    private javax.swing.JLabel Judul;
    private javax.swing.JTable PETVILLE;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfIDHewan;
    private javax.swing.JTextField tfJenisHewan;
    private javax.swing.JTextField tfNamaHewan;
    // End of variables declaration//GEN-END:variables
}
